language: node_js
node_js:
  - "13"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm i -g yarn
  - yarn
  - yarn generate

deploy:
  provider: pages
  edge: true
  cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target_branch: gh-pages
  local_dir: dist
  on:
    branch: master
