language: node_js
node_js:
  - "13"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

before_install:
  - npm i -g yarn
  - npm i -g firebase-tools

install:
  - yarn
  - yarn generate:gh-pages

deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    project: personal-9e1c2
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_ACCESS_TOKEN
    target_branch: gh-pages
    local_dir: dist
    on:
      branch: master
