language: node_js
node_js:
  - "13"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm i -g yarn
  - yarn
  - yarn generate:gh-pages

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_ACCESS_TOKEN
    target_branch: gh-pages
    local_dir: dist
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
  on:
    branch: master
